language: php

php:
  - 5.3
  - 5.4

before_script:
  - pear channel-discover pear.zero.mq
  - pecl install pear.zero.mq/zmq-beta
  - composer self-update
  - composer install --dev

script: phpunit --coverage-text
